apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "my-shipyard"
spec:
  stages:
    - name: "build"
      sequences:
      - name: "ci"
        tasks: 
        - name: "compile"

    - name: "dev"
      sequences:
      - name: "deploy-dev"
        triggeredOn:
          - event: "build.ci.finished"
        tasks: 
        - name: "deploy-dev-env"
      
    - name: "qms"
      sequences:
      - name: "deploy-qms"
        triggeredOn:
          - event: "dev.deploy-dev.finished"
        tasks:
        - name: "approval"
          properties:
            pass: "manual"
            warning: "manual"
        - name: "deploy-qms-env"